services:
  meetnow-db:
    image: postgres:15
    hostname: postgres-host
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=meetnow-password
      - POSTGRES_USER=meetnow-user
      - POSTGRES_DB=meetnow_db

  meetnow-spring:
    build:
      dockerfile: dockerfiles/springapp.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - meetnow-db
    environment:
      WAIT_HOSTS: postgres-host
      SPRING_DATASOURCE_URL: jdbc:postgresql://meetnow-db:5432/meetnow_db
volumes:
  pgdata: