services:
  meetnow-db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=meetnow-password
      - POSTGRES_USER=meetnow-user
      - POSTGRES_DB=meetnow_db

  meetnow-spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - meetnow-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://meetnow-db:5432/
    restart: on-failure
volumes:
  pgdata: