services:
  meetnow-db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=meetnow-password
      - POSTGRES_USER=meetnow-user
      - POSTGRES_DB=meetnow_db
volumes:
  pgdata: